# base-nextjs-prod-pipeline.yml
parameters:
  - name: vmImageName
    default: 'ubuntu-latest'
  - name: installCommand
    default: 'npm install'
  - name: buildCommand
    default: 'npm run build'
  - name: artifactDestination
    default: '$(Build.ArtifactStagingDirectory)'
  - name: deploymentName
    default: ''
  - name: azureSubscription
    default: ''
  - name: resourceGroup
    default: ''
  - name: deployScriptPath
    default: 'scripts/deploy_nextjs.sh'
  - name: deployEnvironment
    default: 'production'
  - name: containerBuild: false
  - name: dockerfilePath
    default: '**/Dockerfile'
  - name: imageRepository
    default: ''
  - name: dockerRegistryServiceConnection
    default: ''
  - name: containerRegistry
    default: ''
  - name: tagPrefix
    default: ''

trigger:
  branches:
    include:
      - main
      - release/*
  tags:
    include:
      - '*'

stages:
- template: templates/stages/nextjs_prod_build_stage.yml
  parameters:
    vmImageName: ${{ parameters.vmImageName }}
    installCommand: ${{ parameters.installCommand }}
    buildCommand: ${{ parameters.buildCommand }}
    artifactDestination: ${{ parameters.artifactDestination }}
    containerBuild: ${{ parameters.containerBuild }}
    dockerfilePath: ${{ parameters.dockerfilePath }}
    imageRepository: ${{ parameters.imageRepository }}
    dockerRegistryServiceConnection: ${{ parameters.dockerRegistryServiceConnection }}
    containerRegistry: ${{ parameters.containerRegistry }}
    tagPrefix: ${{ parameters.tagPrefix }}

- template: templates/stages/nextjs_prod_deploy_stage.yml
  parameters:
    vmImageName: ${{ parameters.vmImageName }}
    environmentName: ${{ parameters.deployEnvironment }}
    deployScriptPath: ${{ parameters.deployScriptPath }}
    artifactPath: ${{ parameters.artifactDestination }}
    deploymentName: ${{ parameters.deploymentName }}
    azureSubscription: ${{ parameters.azureSubscription }}
    resourceGroup: ${{ parameters.resourceGroup }}
