# base-functionapp-pipeline.yml
parameters:
  - name: vmImageName
    default: "ubuntu-latest"
  - name: mavenPomFile
    default: "pom.xml"
  - name: artifactDestination
    default: "$(Build.ArtifactStagingDirectory)"
  - name: functionAppName
    default: ""
  - name: azureSubscription
    default: ""
  - name: resourceGroup
    default: ""
  - name: deployScriptPath
    default: "scripts/deploy_functionapp.sh"
  - name: deployEnvironment
    default: "function-testing"
  # Parameters for static analysis and telemetry:
  - name: sonarProjectKey
    default: ""
  - name: sonarProjectName
    default: ""
  - name: sonarHostUrl
    default: "https://sonarcloud.io"
  - name: sonarLogin
    default: ""
  - name: telemetryEndpoint
    default: ""

trigger:
  branches:
    include:
      - develop
      - release/*
  tags:
    include:
      - "*"

stages:
  - template: templates/stages/functionapp_v2.5_build_stage.yml
    parameters:
      vmImageName: ${{ parameters.vmImageName }}
      mavenPomFile: ${{ parameters.mavenPomFile }}
      artifactDestination: ${{ parameters.artifactDestination }}
      sonarProjectKey: ${{ parameters.sonarProjectKey }}
      sonarProjectName: ${{ parameters.sonarProjectName }}
      sonarHostUrl: ${{ parameters.sonarHostUrl }}
      sonarLogin: ${{ parameters.sonarLogin }}
      telemetryEndpoint: ${{ parameters.telemetryEndpoint }}

  - template: templates/stages/functionapp_v2.5_deploy_stage.yml
    parameters:
      vmImageName: ${{ parameters.vmImageName }}
      environmentName: ${{ parameters.deployEnvironment }}
      deployScriptPath: ${{ parameters.deployScriptPath }}
      artifactPath: ${{ parameters.artifactDestination }}
      functionAppName: ${{ parameters.functionAppName }}
      azureSubscription: ${{ parameters.azureSubscription }}
      resourceGroup: ${{ parameters.resourceGroup }}
