# templates/stages/functionapp_deploy_stage.yml
parameters:
  - name: vmImageName
    type: string
    default: "ubuntu-latest"
  - name: environmentName
    type: string
    default: "" # e.g., 'function-testing'
  - name: deployScriptPath
    type: string
    default: ""
  - name: artifactPath
    type: string
    default: ""
  - name: functionAppName
    type: string
    default: ""
  - name: azureSubscription
    type: string
    default: ""
  - name: resourceGroup
    type: string
    default: ""

stages:
  - stage: Deploy
    displayName: "Deploy Stage - Function App"
    jobs:
      - template: ../jobs/functionapp_v2_deploy_job.yml
        parameters:
          vmImageName: ${{ parameters.vmImageName }}
          environmentName: ${{ parameters.environmentName }}
          deployScriptPath: ${{ parameters.deployScriptPath }}
          artifactPath: ${{ parameters.artifactPath }}
          functionAppName: ${{ parameters.functionAppName }}
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroup: ${{ parameters.resourceGroup }}
