# templates/stages/functionapp_build_stage.yml
parameters:
  - name: vmImageName
    type: string
    default: "ubuntu-latest"
  - name: mavenPomFile
    type: string
    default: ""
  - name: artifactDestination
    type: string
    default: ""
  - name: artifactsFeeds
    type: string
    default: "AD_Applications_Feed"
  - name: sonarProjectKey
    type: string
    default: ""
  - name: sonarProjectName
    type: string
    default: ""
  - name: sonarHostUrl
    type: string
    default: "https://sonarcloud.io"
  - name: sonarLogin
    type: string
    default: ""
  - name: telemetryEndpoint
    type: string
    default: ""

stages:
  - stage: Build
    displayName: "Build Stage - Function App"
    jobs:
      - template: ../jobs/functionapp_v2_build_job.yml
        parameters:
          vmImageName: ${{ parameters.vmImageName }}
          mavenPomFile: ${{ parameters.mavenPomFile }}
          artifactPath: ${{ parameters.artifactDestination }}
          artifactsFeeds: ${{ parameters.artifactsFeeds }}
          sonarProjectKey: ${{ parameters.sonarProjectKey }}
          sonarProjectName: ${{ parameters.sonarProjectName }}
          sonarHostUrl: ${{ parameters.sonarHostUrl }}
          sonarLogin: ${{ parameters.sonarLogin }}
          telemetryEndpoint: ${{ parameters.telemetryEndpoint }}
