# templates/stages/nextjs_prod_deploy_stage.yml
parameters:
  - name: vmImageName
    default: "ubuntu-latest"
  - name: environmentName
    default: "" # e.g., 'production'
  - name: deployScriptPath
    default: ""
  - name: artifactPath
    default: ""
  - name: deploymentName
    default: ""
  - name: azureSubscription
    default: ""
  - name: resourceGroup
    default: ""
stages:
  - stage: Deploy
    displayName: "Deploy Stage - Next.js Production"
    jobs:
      - template: ../jobs/nextjs_prod_deploy_job.yml
        parameters:
          vmImageName: ${{ parameters.vmImageName }}
          environmentName: ${{ parameters.environmentName }}
          deployScriptPath: ${{ parameters.deployScriptPath }}
          artifactPath: ${{ parameters.artifactPath }}
          deploymentName: ${{ parameters.deploymentName }}
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroup: ${{ parameters.resourceGroup }}
