# templates/stages/nextjs_prod_build_stage.yml
parameters:
  - name: vmImageName
    default: "ubuntu-latest"
  - name: installCommand
    default: "npm install"
  - name: buildCommand
    default: "npm run build"
  - name: artifactDestination
    default: ""
  - name: containerBuild
    default: false
  - name: dockerfilePath
    default: "**/Dockerfile"
  - name: imageRepository
    default: ""
  - name: dockerRegistryServiceConnection
    default: ""
  - name: containerRegistry
    default: ""
  - name: tagPrefix
    default: ""
stages:
  - stage: Build
    displayName: "Build Stage - Next.js Production"
    jobs:
      - template: ../jobs/nextjs_prod_build_job.yml
        parameters:
          vmImageName: ${{ parameters.vmImageName }}
          installCommand: ${{ parameters.installCommand }}
          buildCommand: ${{ parameters.buildCommand }}
          artifactPath: ${{ parameters.artifactDestination }}
      - ${{ if eq(parameters.containerBuild, true) }}:
          - template: ../jobs/nextjs_prod_container_build_job.yml
            parameters:
              vmImageName: ${{ parameters.vmImageName }}
              dockerfilePath: ${{ parameters.dockerfilePath }}
              imageRepository: ${{ parameters.imageRepository }}
              dockerRegistryServiceConnection: ${{ parameters.dockerRegistryServiceConnection }}
              containerRegistry: ${{ parameters.containerRegistry }}
              tagPrefix: ${{ parameters.tagPrefix }}
