# templates/jobs/docker_build_job.yml
# Job template for building and publishing Docker images

parameters:
  vmImageName: "ubuntu-latest"
  dockerRegistryServiceConnection: ""
  imageRepository: ""
  containerRegistry: ""

jobs:
  - job: Docker
    displayName: "Build and Publish Docker Image"
    dependsOn: Helm
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
      - task: DownloadSecureFile@1
        name: settings
        inputs:
          secureFile: maven_settings.xml
      - script: |
          TAG=prod-$(git describe --tag $(Build.SourceVersion) --exact-match)
          echo "##vso[task.setvariable variable=tag]$TAG"
          echo "##vso[task.setvariable variable=prodBuild]true"
        displayName: "Set Prod Variables"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      - script: |
          echo "##vso[task.setvariable variable=tag]dev-latest"
        displayName: "Set Dev Variables"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      - script: |
          TAG=qa-$(echo $(Build.SourceBranch) | awk -F/ '{print $NF}')
          echo "##vso[task.setvariable variable=tag]$TAG"
        displayName: "Set QA Variables"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
      - template: ../tasks/ermetic_scan.yml
        parameters:
          imageName: $(${{ parameters.containerRegistry }})/${{ parameters.imageRepository }}:$(tag)
          registryUsername: "$(CONTAINER_REGISTRY_USERNAME)"
          registryPassword: "$(CONTAINER_REGISTRY_PASSWORD)"
      # - ${{ if(eq(variables['prodBuild'], false)) }}:
      - template: ../tasks/docker_build.yml
        parameters:
          dockerfilePath: "**/Dockerfile"
          repository: ${{ parameters.imageRepository }}
          containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
          tags: $(tag)
          additionalArgs: "--secret id=settings,src=$(settings.secureFilePath)"
          # condition: eq(variables['prodBuild'], false)
      # - ${{ if(eq(variables['prodBuild'], false)) }}:
      - template: ../tasks/docker_push.yml
        parameters:
          repository: ${{ parameters.imageRepository }}
          containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
          tags: $(tag)
          # condition: eq(variables['prodBuild'], false)
      # - template: ../tasks/ermetic_scan.yml
      #   parameters:
      #     imageName: "$(containerRegistry)/${{ parameters.imageRepository }}:$(tag)"
      #     registryUsername: "$(CONTAINER_REGISTRY_USERNAME)"
      #     registryPassword: "$(CONTAINER_REGISTRY_PASSWORD)"
      # - ${{ if(eq(variables['prodBuild'], true)) }}:    
      # - template: ../tasks/docker_build.yml
      #   parameters:
      #     dockerfilePath: "**/Dockerfile"
      #     repository: ${{ parameters.imageRepository }}
      #     containerRegistry: "$(prodDockerRegistryServiceConnection)"
      #     tags: "$(tag)"
      #     additionalArgs: "--secret id=settings,src=$(settings.secureFilePath)"
      #     # condition: eq(variables['prodBuild'], true)
      # # - ${{ if(eq(variables['prodBuild'], true)) }}:
      # - template: ../tasks/docker_push.yml
      #   parameters:
      #     repository: ${{ parameters.imageRepository }}
      #     containerRegistry: "$(prodDockerRegistryServiceConnection)"
      #     tags: "$(tag)"
      #     # condition: eq(variables['prodBuild'], true) 