# templates/jobs/java_tests_job.yml
# Job template for executing Java tests

parameters:
  - name: vmImageName
    default: "ubuntu-latest"
  - name: mavenPomFile
    default: ""
  - name: goals
    default: ""
  - name: testResultsFiles
    default: ""
  - name: MAVEN_OPTS
    default: ""

jobs:
  - job: Tests
    displayName: "Execute Tests"
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
      - template: ../tasks/java_tool_installer.yml
        parameters:
          versionSpec: "21"
      - template: ../tasks/maven_authenticate.yml
        parameters:
          artifactsFeeds: "AD_Applications_Feed"
      - template: ../tasks/maven_test.yml
        parameters:
          mavenPomFile: ${{ parameters.mavenPomFile }}
          goals: ${{ parameters.goals }}
          testResultsFiles: ${{ parameters.testResultsFiles }}
          javaHomeOption: "Path"
          jdkDirectory: "/usr/lib/jvm/temurin-21-jdk-amd64"
          mavenVersionOption: "Default"
          mavenOptions: "-Xmx3072m"
      - template: ../tasks/publish_code_coverage.yml
        parameters:
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
