# templates/jobs/nextjs_prod_container_build_job.yml
parameters:
  - name: vmImageName
    type: string
    default: "ubuntu-latest"
  - name: dockerfilePath
    type: string
    default: "**/Dockerfile"
  - name: imageRepository
    type: string
    default: ""
  - name: dockerRegistryServiceConnection
    type: string
    default: ""
  - name: containerRegistry
    type: string
    default: ""
  - name: tagPrefix
    type: string
    default: ""
jobs:
  - job: NextJsContainerBuild
    displayName: "Build, Tag, and Scan Next.js Container"
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
      - template: ../tasks/build_and_scan_container.yml
        parameters:
          dockerfilePath: ${{ parameters.dockerfilePath }}
          imageRepository: ${{ parameters.imageRepository }}
          dockerRegistryServiceConnection: ${{ parameters.dockerRegistryServiceConnection }}
          containerRegistry: ${{ parameters.containerRegistry }}
          tagPrefix: ${{ parameters.tagPrefix }}
