# templates/tasks/docker_build.yml
parameters:
  - name: dockerfilePath
    default: ""
  - name: repository
    default: ""
  - name: containerRegistry
    default: ""
  - name: tags
    default: ""
  - name: additionalArgs
    default: ""

steps:
  - task: Docker@2
    displayName: "Build Docker Image"
    inputs:
      command: build
      dockerfile: ${{ parameters.dockerfilePath }}
      repository: ${{ parameters.repository }}
      containerRegistry: ${{ parameters.containerRegistry }}
      arguments: ${{ parameters.additionalArgs }}
      tags: |
        ${{ parameters.tags }}
