# templates/tasks/docker_push.yml
parameters:
  - name: repository
    type: string
    default: ""
  - name: containerRegistry
    type: string
    default: ""
  - name: tags
    type: string
    default: ""

steps:
  - task: Docker@2
    displayName: "Push Docker Image"
    inputs:
      command: push
      repository: ${{ parameters.repository }}
      containerRegistry: ${{ parameters.containerRegistry }}
      tags: |
        ${{ parameters.tags }}
