# templates/tasks/helm_login.yml
parameters:
  registry: ""
  secretVariable: ""
  userVariable: ""

steps:
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: "echo $(${{ parameters.secretVariable }}) | helm registry login ${{ parameters.registry }} -u $(${{ parameters.userVariable }}) --password-stdin"
    displayName: "Helm Registry Login"
