# templates/tasks/helm_package.yml
parameters:
  - name: chartPath
    type: string
    default: ""
  - name: destination
    type: string
    default: ""

steps:
  - task: HelmDeploy@1
    displayName: "Package Helm Chart"
    inputs:
      command: "package"
      chartPath: ${{ parameters.chartPath }}
      destination: ${{ parameters.destination }}
