# templates/tasks/helm_login.yml
parameters:
  - name: registry
    type: string
    default: ""
  - name: secretVariable
    type: string
    default: ""
  - name: userVariable
    type: string
    default: ""

steps:
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: "echo $($(secretVariable)) | helm registry login ${{ parameters.registry }} -u $($(userVariable)) --password-stdin"
    displayName: "Helm Registry Login"
