# templates/tasks/java_tool_installer.yml
parameters:
  - name: versionSpec
    default: "21"
  - name: jdkArchitectureOption
    default: "x64"
  - name: jdkSourceOption
    default: "PreInstalled"

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: ${{ parameters.versionSpec }}
      jdkArchitectureOption: ${{ parameters.jdkArchitectureOption }}
      jdkSourceOption: ${{ parameters.jdkSourceOption }}
