# templates/tasks/maven_authenticate.yml
parameters:
  - name: artifactsFeeds
    default: ""

steps:
  - task: MavenAuthenticate@0
    displayName: "Authenticate with Azure Artifacts"
    inputs:
      artifactsFeeds: ${{ parameters.artifactsFeeds }}
