# templates/tasks/maven_build_functionapp.yml
parameters:
  - name: mavenPomFile
    default: ""
  - name: goals
    default: "clean package"
  - name: testResultsFiles
    default: "**/surefire-reports/TEST-*.xml"
  - name: javaHomeOption
    default: "Path"
  - name: jdkDirectory
    default: "/usr/lib/jvm/temurin-21-jdk-amd64"
  - name: mavenVersionOption
    default: "Default"
  - name: mavenOptions
    default: "-Xmx3072m"

steps:
  - task: Maven@3
    displayName: "Build Function App with Maven"
    inputs:
      mavenPomFile: ${{ parameters.mavenPomFile }}
      goals: ${{ parameters.goals }}
      publishJUnitResults: true
      testResultsFiles: ${{ parameters.testResultsFiles }}
      javaHomeOption: ${{ parameters.javaHomeOption }}
      jdkDirectory: ${{ parameters.jdkDirectory }}
      mavenVersionOption: ${{ parameters.mavenVersionOption }}
      mavenOptions: ${{ parameters.mavenOptions }}
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
