# templates/tasks/maven_test.yml
parameters:
  - name: mavenPomFile
    default: ""
  - name: goals
    default: ""
  - name: testResultsFiles
    default: ""
  - name: javaHomeOption
    default: "Path"
  - name: jdkDirectory
    default: ""
  - name: mavenVersionOption
    default: "Default"
  - name: mavenOptions
    default: ""

steps:
  - task: Maven@3
    displayName: "Execute Unit Tests"
    inputs:
      mavenPomFile: ${{ parameters.mavenPomFile }}
      goals: ${{ parameters.goals }}
      publishJUnitResults: true
      testResultsFiles: ${{ parameters.testResultsFiles }}
      javaHomeOption: ${{ parameters.javaHomeOption }}
      jdkDirectory: ${{ parameters.jdkDirectory }}
      mavenVersionOption: ${{ parameters.mavenVersionOption }}
      mavenOptions: ${{ parameters.mavenOptions }}
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
